version: '3.3'
services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
    server:
      build:
        context: .
        dockerfile: Dockerfile
      command: bash -c "
        python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000
        && python manage.py loaddata
        "

      volumes:
        - ./source/:/code
      ports:
        - '8000:8000'
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      depends_on:
        - db
